### ISSUE TITLE
Blobtools view can't validate raw metadata

### ISSUE THREAD

**Issue by caioald** [blobtoolkit/blobtoolkit#104]
After a while of figuring out how to run blobtools I managed to go successfully through the pipeline except for the blobtools view.

The validate_dataset.log within the view only states this:
NOT VALID: Error while testing raw metadata against schema
data.y must match pattern ^[A-Za-z0-9_]+$

And actually when running blobtools validate I get the same.

Is it something wrong with file names? Which file I could upload here so you could have a look?

Thanks in advance!

**Comment by rjchallis** [comment]
This is getting picked up when it validates the `plot.y` field in `meta.json`, the field name is being tested against the schema below, which is restricted to alphanumeric characters. This parameter value should be the first coverage file that you loaded, so it looks like it must be the name of your read file that is causing it not to validate.

```
"y": {
      "description": "y axis field ID",
      "type": "string",
      "pattern": "^[A-Za-z0-9_]+$"
    }
```

If you'd like to share your meta.json file and a list of filenames in the BlobDir, I can look to see if that is the problem, and suggest which file name(s) to change to make it valid without having to re-run blobtools.

**Comment by caioald** [comment]
Thanks Richard,
It indeed has some underscores in the name.

 "plot": {
  "z": "length",
  "x": "gc",
  "y": "Ac2012-1_IS350_Clean_cov",

Can you tell me then which files should I change the names, please?

[meta.json.txt](https://github.com/blobtoolkit/blobtoolkit/files/9724071/meta.json.txt)
[BlobDir_files.txt](https://github.com/blobtoolkit/blobtoolkit/files/9724076/BlobDir_files.txt)

**Comment by caioald** [comment]
Thanks again Richard,
I tried replacing as you mentioned and the validation passed, but I started getting a new error (see below).
So I decided to change my file names, and change all the prefixes in my config.yaml file and start running it again, it should work now.

New error:

`Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job stats:
job                 count    min threads    max threads
----------------  -------  -------------  -------------
all                     1              1              1
checksum_files          1              1              1
copy_blobdir            1              1              1
generate_images         1              1              1
generate_summary        1              1              1
validate_dataset        1              1              1
total                   6              1              1

Select jobs to execute...

[Thu Oct  6 13:33:38 2022]
rule copy_blobdir:
    input: ../blobtools/nanopore
    output: nanopore.copied, nanopore/Ac2012-1_IS350_Clean_cov.json, nanopore/Ac2012-1_filtered_reads_cov.json, nanopore/buscogenes_phylum_positions.json, nanopore/agaricales_odb10_busco.json, nanopore/identifiers.json
    log: logs/nanopore/copy_blobdir.log
    jobid: 5
    benchmark: logs/nanopore/copy_blobdir.benchmark.txt
    wildcards: blobdir=nanopore
    resources: tmpdir=/scratch/37790851

(mkdir -p nanopore         && rsync -av ../blobtools/nanopore/ nanopore/         && touch nanopore.copied) 2> logs/nanopore/copy_blobdir.log
Waiting at most 60 seconds for missing files.
MissingOutputException in line 42 of /home/projects/ku_00099/apps/blobtoolkit/insdc-pipeline/view.smk:
Job Missing files after 60 seconds:
nanopore/Ac2012-1_IS350_Clean_cov.json
nanopore/Ac2012-1_filtered_reads_cov.json
This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.
Job id: 5 completed successfully, but some output files are missing. 5
Removing output files of failed job copy_blobdir since they might be corrupted:
nanopore.copied, nanopore/buscogenes_phylum_positions.json, nanopore/agaricales_odb10_busco.json, nanopore/identifiers.json
Trying to restart job 5.
Select jobs to execute...

[Thu Oct  6 13:34:38 2022]
rule copy_blobdir:
    input: ../blobtools/nanopore
    output: nanopore.copied, nanopore/Ac2012-1_IS350_Clean_cov.json, nanopore/Ac2012-1_filtered_reads_cov.json, nanopore/buscogenes_phylum_positions.json, nanopore/agaricales_odb10_busco.json, nanopore/identifiers.json
    log: logs/nanopore/copy_blobdir.log
    jobid: 5
    benchmark: logs/nanopore/copy_blobdir.benchmark.txt
    wildcards: blobdir=nanopore
    resources: tmpdir=/scratch/37790851

(mkdir -p nanopore         && rsync -av ../blobtools/nanopore/ nanopore/         && touch nanopore.copied) 2> logs/nanopore/copy_blobdir.log
Waiting at most 60 seconds for missing files.
MissingOutputException in line 42 of /home/projects/ku_00099/apps/blobtoolkit/insdc-pipeline/view.smk:
Job Missing files after 60 seconds:
nanopore/Ac2012-1_IS350_Clean_cov.json
nanopore/Ac2012-1_filtered_reads_cov.json
This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.
Job id: 5 completed successfully, but some output files are missing. 5
Removing output files of failed job copy_blobdir since they might be corrupted:
nanopore.copied, nanopore/buscogenes_phylum_positions.json, nanopore/agaricales_odb10_busco.json, nanopore/identifiers.json
Trying to restart job 5.
Select jobs to execute...

[Thu Oct  6 13:35:38 2022]
rule copy_blobdir:
    input: ../blobtools/nanopore
    output: nanopore.copied, nanopore/Ac2012-1_IS350_Clean_cov.json, nanopore/Ac2012-1_filtered_reads_cov.json, nanopore/buscogenes_phylum_positions.json, nanopore/agaricales_odb10_busco.json, nanopore/identifiers.json
    log: logs/nanopore/copy_blobdir.log
    jobid: 5
    benchmark: logs/nanopore/copy_blobdir.benchmark.txt
    wildcards: blobdir=nanopore
    resources: tmpdir=/scratch/37790851

(mkdir -p nanopore         && rsync -av ../blobtools/nanopore/ nanopore/         && touch nanopore.copied) 2> logs/nanopore/copy_blobdir.log
Waiting at most 60 seconds for missing files.
MissingOutputException in line 42 of /home/projects/ku_00099/apps/blobtoolkit/insdc-pipeline/view.smk:
Job Missing files after 60 seconds:
nanopore/Ac2012-1_IS350_Clean_cov.json
nanopore/Ac2012-1_filtered_reads_cov.json
This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.
Job id: 5 completed successfully, but some output files are missing. 5
Removing output files of failed job copy_blobdir since they might be corrupted:
nanopore.copied, nanopore/buscogenes_phylum_positions.json, nanopore/agaricales_odb10_busco.json, nanopore/identifiers.json
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /blobtools4/view/.snakemake/log/2022-10-06T133337.810311.snakemake.log
`

**Comment by rjchallis** [comment]
Yes, the full pipeline should work now. I hadn't anticipated the pipeline complaining about the changed file names as this was so close to the final step that I was just considering how to get the dataset past the validation. If you still have the BlobDir that should be ready to load into the viewer without needing to re-run everything.

**Comment by caioald** [comment]
Awesome, I decided to run from the begining to make sure all would go smooth.
And yes, worked perfectly with the new file names and prefixes.
Thank you very much.
