### ISSUE TITLE
help please Plotting blobtools output files getting some statistics between different datasets

### ISSUE THREAD

**Issue by Sabrin2020** [blobtoolkit/blobtoolkit#108]
Can any one please help me which output files from blobtools2 I can use to do plots like this one which I found in biostars
<img width="786" alt="image" src="https://user-images.githubusercontent.com/59876705/195911160-c477989f-e3c4-4200-9fc3-a6cff9189fa2.png">

I need to have statistics of what I have there and be able to detect comparisons between species and locations based on plotting some stacked bars like this one above.

One major concern to me is to find the info in the highlighted following Photo but for the sample set I am plotting not for the reference to use it for doing some statistics
<img width="868" alt="image" src="https://user-images.githubusercontent.com/59876705/195911906-b8da59dd-d1e7-47f2-af25-28effa732e2c.png">
 How can i get it for the data set if what is in that plot highlighted belong to the reference??

**Comment by sujaikumar** [comment]
Hi @Sabrin2020

If you go to Filters (top menu) and choose "table" view (just under the word "Filters"), then you get in a table view all the contig/scaffold lengths/GC/cov and assignments using different methods at different taxonomic ranks

On the top right of the table view is a "csv" button - clicking on that will download the entire table. Once you have that table you can customise the statistics/visualisations in any way you like using other tools/plotting libraries.

Hope that helps
