### ISSUE TITLE
SVG files not displayed properly in Ai, Gimp, Inkscape, and Corel Vector

### ISSUE THREAD

**Issue by sven1990** [blobtoolkit/blobtoolkit#126]
Hi, 
I need to use the svg files generated by BlobToolKit to be able to adjust the font size, as it is quite small in the plots. 
However, the svg files are not properly displayed in any graphics program I've tried. 

For example, when I try to open the snail plot in Adobe Illustrator 2023 (similar in Inkscape), I get the message that the path text is reduced, and then I get an "Open Sans: unknown error" message followed by this image:
<img width="737" alt="Bildschirmfoto 2022-12-14 um 13 43 15" src="https://user-images.githubusercontent.com/36346531/207599132-42dfa555-4e5c-4318-b72f-8309a309cc30.png">

I can remove the main black overlay, but then there is still an issue with the GC coloring for small scaffolds:
<img width="598" alt="Bildschirmfoto 2022-12-14 um 13 48 52" src="https://user-images.githubusercontent.com/36346531/207599477-ff2d417a-650b-42a8-aa9d-c03573e4b964.png">

Gimp removes all labels on the plot, and Corel Vector, for whatever reason, messes up the label numbers and placement:
<img width="795" alt="Bildschirmfoto 2022-12-14 um 13 52 48" src="https://user-images.githubusercontent.com/36346531/207600339-28e45673-7d59-4afc-90c4-afdd669a9540.png">

Thanks for your help!

Sven

**Comment by sven1990** [comment]
@rjchallis 
Thank you very much for your quick response. What is the easiest way for me to fix this issue on my server? I installed blobtoolkit with pip.

**Comment by rjchallis** [comment]
I've just pushed a version 3.5.2 release to PyPi that has this fix so you should be able to pip install this now
