### ISSUE TITLE
Website Down

### ISSUE THREAD

**Issue by RexRowan** [blobtoolkit/blobtoolkit#170]
The main website does not load.

**Comment by sujaikumar** [comment]
Hi. We’re aware of a temporary issue with the BTK server. If you just add the word “-sanger” after the word blobtoolkit in the URL, it will take you to a backup server till the main site comes back up:
For example:
    [blobtoolkit.genomehubs.org/view/Metazoa](http://blobtoolkit.genomehubs.org/view/Metazoa)
should become:
    [blobtoolkit-sanger.genomehubs.org/view/Metazoa](http://blobtoolkit-sanger.genomehubs.org/view/Metazoa)

**Comment by RexRowan** [comment]
Thanks, it's up now!
