### ISSUE TITLE
ERROR: Unable to parse /blobtoolkit/databases/ncbi_taxdump/nodes.dmp

### ISSUE THREAD

**Issue by jaylward2** [blobtoolkit/blobtoolkit#172]
Hello

I am for the first time trying to run BTK in Docker and I ran into an issue with the taxdump database.

```
docker run -it  -u $UID:$GROUPS \
     -v $(pwd):/blobtoolkit/datasets \
     -v $(pwd):/blobtoolkit/data \
     genomehubs/blobtoolkit:latest \
blobtools add --replace \
     --busco data/busco_fun10/run*/full_table.tsv \
     --busco data/busco_sor10/run*/full_table.tsv \
     --cov data/coverage/sorted.bam \
     --hits data/blast/*.ncbi.blastn.out \
     --hits data/blast/*.diamond.blastx.out \
     --taxdump databases/ncbi_taxdump datasets/blob_can
```
Terminal output:
Loading mapping data from data/coverage/sorted.bam as sorted
[+]        Locating alignments: ████████████████████████████████████████     586/586                                                       Parsing taxdump
ERROR: Unable to parse /blobtoolkit/databases/ncbi_taxdump/nodes.dmp.

When I use “ls”, the databases/ncbi_taxdump folder seems to be empty

EDIT: I was able to work around this for now by downloading my own taxdump database, mounting it to the container and then pointing —taxdump at that.

**Comment by sujaikumar** [comment]
Hi there. Apologies for that. Yes, the btk container doesn't come with the taxdump database - it does need to be downloaded/mounted/pointed to, exactly as you said. I need to improve our documentation. Thanks for putting the solution up here for anyone else with the same problem.
