### ISSUE TITLE
An error occurs when using blobtools create

### ISSUE THREAD

**Issue by maruiqi0710** [blobtoolkit/blobtoolkit#178]
I run
```
fasta_file=/path/to/scaffolds.fasta
out_dir=../out_dir

blobtools create \
--fasta $fasta_file \
$out_dir
```

but report:

> Traceback (most recent call last):
>   File "/Software/miniconda3/envs/BlobToolKit/lib/python3.11/site-packages/blobtools/lib/fetch.py", line 67, in fetch_metadata
>     meta = kwargs["meta"]
>            ~~~~~~^^^^^^^^
> KeyError: 'meta'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Software/miniconda3/envs/BlobToolKit/bin/blobtools", line 8, in <module>
>     sys.exit(cli())
>              ^^^^^
>   File "/Software/miniconda3/envs/BlobToolKit/lib/python3.11/site-packages/blobtools/blobtools.py", line 105, in cli
>     sys.exit(subcommand())
>              ^^^^^^^^^^^^
>   File "/Software/miniconda3/envs/BlobToolKit/lib/python3.11/site-packages/blobtools/lib/add.py", line 203, in cli
>     main(args)
>   File "/Software/miniconda3/envs/BlobToolKit/lib/python3.11/site-packages/blobtools/lib/add.py", line 123, in main
>     meta = fetch_metadata(args["DIRECTORY"], **args)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Software/miniconda3/envs/BlobToolKit/lib/python3.11/site-packages/blobtools/lib/fetch.py", line 70, in fetch_metadata
>     meta = file_io.load_yaml("%s/meta.json" % path_to_dataset)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Software/miniconda3/envs/BlobToolKit/lib/python3.11/site-packages/blobtools/lib/file_io.py", line 86, in load_yaml
>     data = read_file(filename)
>            ^^^^^^^^^^^^^^^^^^^
>   File "/Software/miniconda3/envs/BlobToolKit/lib/python3.11/site-packages/blobtools/lib/file_io.py", line 39, in read_file
>     with stream_file(filename) as fh:
> TypeError: 'NoneType' object does not support the context manager protocol

The output directory is empty.

I install BlobToolKit as the following command:
```
conda create -n BlobToolKit
conda activate BlobToolKit
mamba install -c conda-forge python
pip install blobtoolkit[full]
```

blobtoolkit version: 4.1.5

**Comment by rjchallis** [comment]
Looks like this is a bug when running under python 3.11, could you retry with `python=3.9` as that is the version running in the containers so should be most reliable
