### ISSUE TITLE
Larger legends for the blobplots

### ISSUE THREAD

**Issue by eeaunin** [blobtoolkit/blobtoolkit#182]
Hello.
I would like to have an option in BlobToolKit to make the blobplot legend as large as the plot itself. Currently the legend in the upper right corner of the plot is always too small to be readable when the plot is put on a PowerPoint slide. I know there is the "use larger fonts" option but even when using this, the legend is too small. When putting blobplots on PowerPoint slides I keep having to manually duplicate the plot and then crop one of the copies to make a legend that's large enough to be readable. Example: [https://docs.google.com/presentation/d/1p2K6KHiEbDW0NVHd39voaIx3MR5KgV0tx3Bkc64hf38/edit?usp=sharing](https://docs.google.com/presentation/d/1p2K6KHiEbDW0NVHd39voaIx3MR5KgV0tx3Bkc64hf38/edit?usp=sharing). It would be great if BlobToolKit had an option for automatically placing the legend in a larger area next to the blobplot, instead of squashing the legend into the upper right corner of the plot. 
Best regards,
Eerik

**Comment by rjchallis** [comment]
Hi Eerik

This is something that is now possible using [blobtk](https://github.com/blobtoolkit/blobtk), which I'm working on to speed up some of the data imports and allow plot generation without a browser. The basic plots are all available (but the full range of blob plot variants are not yet supported) and it is possible to draw only the legend, and even to use more than 10 colours for the categories. 

There are install instructions at https://github.com/blobtoolkit/blobtk/wiki and an example of legend only plotting at https://github.com/blobtoolkit/blobtk/wiki/blobtk-plot#legend-only

I'm planning to work on integrating the blobtk plots into blobtoolkit, but hope this helps in the meantime.

Rich

**Comment by eeaunin** [comment]
Hi Richard,
Thanks a lot! I will try these things out with blobtk.
Best regards,
Eerik
