### ISSUE TITLE
no-hits with species, genus and family level annotation

### ISSUE THREAD

**Issue by ChathumadaviE** [blobtoolkit/blobtoolkit#183]
Hi

I was able to run blobtoolkit on my draft assembly and this is how the blobs look like.

![image](https://github.com/blobtoolkit/blobtoolkit/assets/116005509/0c98808b-343a-40ae-b883-1581254a9975)

My target species is an arthropod and it has lots of no-hits. When examined the no-hits I found odd results where there are busco annotations at family, genus and species level but no-hits at phylum and class level. Below I attached the results table.

![image](https://github.com/blobtoolkit/blobtoolkit/assets/116005509/8affa3bb-3a30-4f8e-b350-60c1ae5c35a7)

Could you please help interpret this and give me advice on how to filter the blobs for this arthropod organism? Should I just select only the arthropod blobs and no-hits without any annotations which lie within the arthropod gc level and coverage region?

Thanks!

**Comment by rjchallis** [comment]
these results are coming from 2 classes of tax rule:

- `buscogenes*` runs a diamond search for the sequences of BUSCO genes identified on the contains so will return no-hit for any contain with no BUSCOs. This is usually a good choice for highly contiguous assemblies, but as you have seen can leave smaller contains unannotated.
- `buscoregions*` breaks the contigs up into up to 10 chunks then runs a diamond search for the 100kb regions around the highest density of BUSCO genes in a chunk, or just for a 100kb region in the middle of the chunk if it has no BUSCOs. If no hits are found, it also runs a BLAST search against nt so has a much betted chance of finding hits and is more suited to annotating fragmented assemblies.

So for this example, you should probably focus on just the `buscoregions*` tax rules, and you should find that any config with hots at one rank has hits at all ranks, even if there are no `buscogenes*` hits

**Comment by ChathumadaviE** [comment]
Thank you for your response! Really appreciate it.
