### ISSUE TITLE
Adding tiara

### ISSUE THREAD

**Issue by TCHeaven** [blobtoolkit/blobtoolkit#193]
When I try to add tiara categories to BTK

`blobtools add \
    --text /jic/scratch/groups/Saskia-Hogenhout/tom_heaven/Psyllidae/assembly/genome/T_urticae/hifiasm_19.5/715m/12/2/3.0/0.5/tiara/T_urticae_715m_12_2_3.0_0.5.tiara \
    --text-delimiter "\t" \
    --text-cols "sequence_id=identifiers,class_fst_stage=tiara" \
    --text-header \
    --key plot.cat=tiara \
    ./Turt1223005_blobdir`

and then try to open the BlobDir in viewer there are no longer any plots available (without adding tiara info I had a blobplot + snail plot + busco plot etc) and the plotting area is blank.
![image](https://github.com/blobtoolkit/blobtoolkit/assets/46782239/b33f5a87-032e-423b-b48f-ef74e40dbccc)

Is adding other categorical values to contigs incompatible with colouring with hit files from blast? Am I doing something else wrong?

T_urticae_715m_12_2_3.0_0.5.tiara looks like this:
sequence_id     class_fst_stage class_snd_stage org     bac     arc     euk     unk1    pla     unk2    mit
ptg000001l      eukarya n/a     0.017073        0.013154        0.000760        0.969014        0.000000        n/a     n/a     n/a
ptg000002l      eukarya n/a     0.000003        0.000000        0.001369        0.998628        0.000000        n/a     n/a     n/a
ptg000003l      eukarya n/a     0.000000        0.000000        0.000000        1.000000        0.000000        n/a     n/a     n/a
ptg000004l      eukarya n/a     0.000089        0.246809        0.002224        0.750878        0.000000        n/a     n/a     n/a
ptg000005l      eukarya n/a     0.000002        0.000000        0.000000        0.999998        0.000000        n/a     n/a     n/a
etc.

I have received no errors when running either BTK or viewer.

**Comment by rjchallis** [comment]
That command looks almost right but it looks like you've set the default plot category to a category name that doesn't exist. `--text /path/to/T_urticae_715m_12_2_3.0_0.5.tiara` creates a category with the same name as the file so if you scroll down through the filters in the viewer you should see a category named `T_urticae_715m_12_2_3.0_0.5.tiara` that you can activate and set as the plot category by clicking the category icon.

To use this as the default category you could either use `--key plot.cat=T_urticae_715m_12_2_3.0_0.5.tiara` to set the default category to match the file name or change the category name to tiara by adding `=tiara` to the end of `--text /path/to/T_urticae_715m_12_2_3.0_0.5.tiara=tiara`.

**Comment by TCHeaven** [comment]
Thank you! I think 'clicking the category icon' is what I was missing 😊
