### ISSUE TITLE
Error with Parsing taxdump

### ISSUE THREAD

**Issue by Edouard94** [blobtoolkit/blobtoolkit#195]
Hello,

I hope you would be able to help me with the following issue. This work is done on Galaxy EU server.

I created an initial blob directory with an assembled genome and the last NCBI taxdump file:
`mkdir -p './Blobdir' && mkdir -p './taxdump' && ln -s '/data/dnb09/galaxy_db/files/6/f/3/dataset_6f3776c3-f7f3-492d-bb54-73e49e58adbf.dat' 'taxdump.tar' && tar -xf 'taxdump.tar' -C './taxdump' && ln -s '/data/dnb09/galaxy_db/files/e/0/7/dataset_e07e1fd9-cced-440a-8641-4e35035b2b14.dat' 'assembly.fasta' && blobtools create --fasta 'assembly.fasta' --taxid 6029 --taxdump './taxdump' './Blobdir' && tar -C ./Blobdir -zcvf Blobdir.tgz .`

Then I added to the created blob directory a busco table and a diamond table coming from a limited search for my sequenced organism and against the Uniprot database:
`mkdir -p './Blobdir' && mkdir -p './taxdump' && ln -s '/data/dnb09/galaxy_db/files/6/f/3/dataset_6f3776c3-f7f3-492d-bb54-73e49e58adbf.dat' 'taxdump.tar' && tar -xf 'taxdump.tar' -C './taxdump' && tar -zxf '/data/dnb09/galaxy_db/files/1/1/a/dataset_11afc836-d15e-4ba5-8681-c5e1ff38e2ac.dat' -C './Blobdir' && ln -s '/data/dnb09/galaxy_db/files/5/d/3/dataset_5d3b25bb-4090-4e8b-bea3-cd8d4696c1ec.dat' './busco_results.tab' && ln -s '/data/dnb09/galaxy_db/files/3/0/e/dataset_30e6c338-5ddf-4b0e-bbf4-d14343e63656.dat' './blast_results.tab' && blobtools add --threads ${GALAXY_SLOTS:-8} --taxdump './taxdump' --busco './busco_results.tab' --hits './blast_results.tab' --hits-cols '1=qseqid,2=sseqid,3=sstart,4=send,5=evalue,6=bitscore,7=staxids' --taxrule bestsum --evalue 1.0 --hit-count 10 --bitscore 1.0   './Blobdir' && tar -C ./Blobdir -zcvf Blobdir.tgz .`

So far so good. But when I want to add a diamond table without organism restriction and against the NCBI nr databse (ncbi_nr_2023-07-28), I get the following error.
Here is the command used:
`mkdir -p './Blobdir' && mkdir -p './taxdump' && ln -s '/data/dnb09/galaxy_db/files/2/d/d/dataset_2ddf9926-58b2-495d-9e11-dd6c02dda81b.dat' 'taxdump.tar' && tar -xf 'taxdump.tar' -C './taxdump' && tar -zxf '/data/dnb09/galaxy_db/files/1/1/a/dataset_11afc836-d15e-4ba5-8681-c5e1ff38e2ac.dat' -C './Blobdir' && ln -s '/data/dnb09/galaxy_db/files/5/d/3/dataset_5d3b25bb-4090-4e8b-bea3-cd8d4696c1ec.dat' './busco_results.tab' && ln -s '/data/dnb09/galaxy_db/files/8/1/a/dataset_81abdccf-ed08-438d-a547-0b76d7762484.dat' './blast_results.tab' && blobtools add --threads ${GALAXY_SLOTS:-8} --taxdump './taxdump' --busco './busco_results.tab' --hits './blast_results.tab' --hits-cols '1=qseqid,2=sseqid,3=qstart,4=qend,5=evalue,6=bitscore,7=staxids' --taxrule bestsum --evalue 1.0 --hit-count 10 --bitscore 1.0   './Blobdir' && tar -C ./Blobdir -zcvf Blobdir.tgz .`

And here is the error:
```
Traceback (most recent call last):
  File "/opt/conda/envs/btk_env/bin/blobtools", line 8, in <module>
    sys.exit(cli())
  File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/blobtools/blobtools.py", line 105, in cli
    sys.exit(subcommand())
  File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/blobtools/lib/add.py", line 203, in cli
    main(args)
  File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/blobtools/lib/add.py", line 149, in main
    parsed = field["module"].parse(
  File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/blobtools/lib/hits.py", line 541, in parse
    blast = parse_blast(
  File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/blobtools/lib/hits.py", line 83, in parse_blast
    taxid = row[cols["staxids"]]
IndexError: list index out of range
```

I have made sure that the --hits-cols option was respecting my diamond tabular output, and I also tried to use an older tax dump file corresponding to the date of the reference database used (ncbi_nr_2023-07-28). I don't get why I have an issue with the taxids and the taxdump file parsing, any input would be very helpful!

Thanks,
Edouard

**Comment by rjchallis** [comment]
Hi Edouard, Could you share the first few lines of the blast files (both the one that worked and the one that didn't) so I can see what the input files look like.

**Comment by Edouard94** [comment]
Hi @rjchallis,

Thank you for your response.

So here is the blast that worked (from Uniprot db restricted to microsporidia):
![image](https://github.com/blobtoolkit/blobtoolkit/assets/60606060/e08c3d79-77d7-4d88-a442-2d6695f7fd35)

And the one that did not (from NCBI database):
![image](https://github.com/blobtoolkit/blobtoolkit/assets/60606060/0aef36ea-1395-494d-8cf9-bb42018fa7d5)

I am just realising that the blast from the NCBI db has multiple taxon separated by ';'. But it should not be an issue right?

Best,
Edouard

**Comment by rjchallis** [comment]
Thanks. The files look fine - and the taxid separator shouldn't be a problem - so I took another look at the commands, the successful one has:
```
--hits-cols '1=qseqid,2=sseqid,3=sstart,4=send,5=evalue,6=bitscore,7=staxids' \
```
while the failing one has:
```
--hits-cols '1=qseqid,2=sseqid,3=qstart,4=qend,5=evalue,6=bitscore,7=staxids'
```
The q vs s prefix to these column names can cause problems as there was a bug in the docs and the code which I then changed to try to accommodate either varient. If you change the second command to `3=sstart,4=send` that may help

**Comment by Edouard94** [comment]
Hi Richard,

Ah yes I tried both ways actually, but it doesn't resolve the issue. I ran it again with the NCBI blast and changed the --hits-cols:

Cmd ran again
`mkdir -p './Blobdir' && mkdir -p './taxdump' && ln -s '/data/dnb09/galaxy_db/files/6/f/3/dataset_6f3776c3-f7f3-492d-bb54-73e49e58adbf.dat' 'taxdump.tar' && tar -xf 'taxdump.tar' -C './taxdump' && tar -zxf '/data/dnb09/galaxy_db/files/1/1/a/dataset_11afc836-d15e-4ba5-8681-c5e1ff38e2ac.dat' -C './Blobdir' && ln -s '/data/dnb09/galaxy_db/files/5/d/3/dataset_5d3b25bb-4090-4e8b-bea3-cd8d4696c1ec.dat' './busco_results.tab' && ln -s '/data/dnb09/galaxy_db/files/9/d/7/dataset_9d7a7423-c1e7-451f-b37f-15413161b9f6.dat' './blast_results.tab' && blobtools add --threads ${GALAXY_SLOTS:-8} --taxdump './taxdump' --busco './busco_results.tab' --hits './blast_results.tab' --hits-cols '1=qseqid,2=sseqid,3=sstart,4=send,5=evalue,6=bitscore,7=staxids' --taxrule bestsum --evalue 1.0 --hit-count 10 --bitscore 1.0   './Blobdir' && tar -C ./Blobdir -zcvf Blobdir.tgz .`

Error report
```
Traceback (most recent call last):
  File "/opt/conda/envs/btk_env/bin/blobtools", line 8, in <module>
    sys.exit(cli())
  File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/blobtools/blobtools.py", line 105, in cli
    sys.exit(subcommand())
  File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/blobtools/lib/add.py", line 203, in cli
    main(args)
  File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/blobtools/lib/add.py", line 149, in main
    parsed = field["module"].parse(
  File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/blobtools/lib/hits.py", line 541, in parse
    blast = parse_blast(
  File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/blobtools/lib/hits.py", line 83, in parse_blast
    taxid = row[cols["staxids"]]
IndexError: list index out of range
```

So this does not seem to solve the error...

Ed

PS the cmd that produced the blast output not working with blob:
`ln -s /data/db/databases/diamond/ncbi_nr/2023-07-28/ncbi_nr_2023-07-28.fa.dmnd ./database.dmnd  &&  diamond blastx --quiet --threads "${GALAXY_SLOTS:-12}" --db ./database --query '/data/dnb09/galaxy_db/files/e/0/7/dataset_e07e1fd9-cced-440a-8641-4e35035b2b14.dat' --query-gencode '1' --strand 'both' --min-orf 1   --outfmt '6' qseqid sseqid qstart qend evalue bitscore staxids --out '/data/jwd02f/main/063/748/63748186/outputs/dataset_9d7a7423-c1e7-451f-b37f-15413161b9f6.dat' --unal 0   --compress '0'   --algo 0 --matrix 'BLOSUM62' --comp-based-stats '1' --masking '1'   --max-target-seqs '25'   --evalue '0.001'  --id '0' --query-cover '0' --subject-cover '0' --block-size '2.0'  --motif-masking 0`

And the one that worked, they should be exactly the same output, only the database is different
`ln -s /data/db/databases/diamond/uniprot_swissprot_2023_03/uniprot_swissprot_2023_03.fa.dmnd ./database.dmnd  &&  diamond blastx --quiet --threads "${GALAXY_SLOTS:-12}" --db ./database --query '/data/dnb09/galaxy_db/files/e/0/7/dataset_e07e1fd9-cced-440a-8641-4e35035b2b14.dat' --query-gencode '1' --strand 'both' --min-orf 1   --outfmt '6' qseqid sseqid qstart qend evalue bitscore staxids --out '/data/jwd02f/main/062/303/62303168/outputs/dataset_30e6c338-5ddf-4b0e-bbf4-d14343e63656.dat' --unal 0   --compress '0'   --algo 0 --matrix 'BLOSUM62' --comp-based-stats '1' --masking '1'   --max-target-seqs '25'   --evalue '0.001'  --id '0' --query-cover '0' --subject-cover '0' --block-size '2.0' --taxonlist '6029'  --motif-masking 0`

**Comment by Edouard94** [comment]
PS: I also tried to run the cmd with the blast file where I removed all the lines that had multiple taxons separated by ';'. But it did not change the error.

**Comment by rjchallis** [comment]
I've just been looking at how to reproduce this error and get the same message if the blast output file has an incomplete row. Can you check that there are no missing values or incomplete rows in your blast output.
