### ISSUE TITLE
blobtools command not found in /blobtoolkit/blobtools2/

### ISSUE THREAD

**Issue by jdmillwood** [blobtoolkit/blobtoolkit#55]
I recently installed Blobtools2 using the directions found at https://blobtoolkit.genomehubs.org/install/ I followed everything correctly, but when I tried to run it I could not call the "blobtools" command. I then looked in the blobtools2 directory, and the command isn't there. Do I need to run a setup command or use make to do anything? I do not recall needing to do that in the past (I had an older version installed), and I don't see that anywhere in the instructions. I tried installing with pip, but there were multiple issues. The main one being the version of selenium. Any help would be appreciated. Thanks.

**Comment by sujaikumar** [comment]
Hi there. We are in the process of cleaning up the old documentation. The latest pip install command is now the recommended way - see the README.md at https://github.com/blobtoolkit/blobtools2

Can you paste the error messages you got with `pip install blobtoolkit` ? Thanks!

**Comment by jdmillwood** [comment]
Thanks for the reply. I figured out the issue with `pip install blobtoolkit`. I just had to create a conda environment because our installed python version was old and had outdated modules/libraries.
