### ISSUE TITLE
Blobtools filter TypeError when using --output

### ISSUE THREAD

**Issue by pgonzale60** [blobtoolkit/blobtoolkit#74]
Hi Rich,

I'm trying to create a new blobdir from from a filtered dataset, but I get the following error:
```
Traceback (most recent call last):
  File "/blobtoolkit/blobtools2/lib/filter.py", line 381, in <module>
    main()
  File "/blobtoolkit/blobtools2/lib/filter.py", line 257, in main
    create_filtered_dataset(meta, args['DATASET'], args['--output'], indices)
  File "/blobtoolkit/blobtools2/lib/filter.py", line 220, in create_filtered_dataset
    full_values = full_field.expand_values()
  File "/blobtoolkit/blobtools2/lib/field.py", line 322, in expand_values
    arr_values[slot] = keys[arr_values[slot]]
TypeError: list indices must be integers or slices, not NoneType
```

The command is
```
singularity exec blobtoolkit_3.1.10.sif blobtools filter \
     --query-string "http://localhost:8080/view/all/dataset/nxOscSpen2/blob?m6e_cov--Min=1.00&buscoregions_phylum--Keys=2&gc--Min=0.250" \
     --output testBlob \
     nxOscSpen
```

I get this error in the singularity images of blobtoolkit 3.1.10, 2.6.3, 2.5.0 and 1.3.4.
Filtering the fasta assembly file works without error.

Please find the compressed blobDir [here](https://oscheius-genomics.cog.sanger.ac.uk/oscheius/btk/nxOscSpen2.tar).

Is this a bug or I am missing something?

Best wishes,
Pablo

**Comment by rjchallis** [comment]
Hi Pablo

Thanks for letting me know about this. I've found the bug so it will be fixed in the next release.
